ci:
  autoupdate_schedule: monthly

repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.0
  hooks:
  - id: mypy
    name: Lint code (mypy)
    language: python
    types: [python]
    require_serial: true
    args: [--config-file=pyproject.toml]
    additional_dependencies: [qgis-stubs]
    exclude: (.*/plugin\.py)|(.*/provider\.py)|(.*/test.*)|(PolygonsParallelToLine/__init__\.py)
- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
    additional_dependencies:
    - isort
- repo: https://github.com/ambv/black
  rev: 23.11.0
  hooks:
  - id: black
    language_version: python
    args: [--line-length=120]
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    name: Lint code (flake8)
    additional_dependencies:
    - flake8==4.0.1
    - flake8-broken-line==0.4.0
    - flake8-bugbear==22.1.11
    - flake8-builtins==1.5.3
    - flake8-comprehensions==3.8.0
    - flake8-eradicate==1.2.0
    - flake8-isort==4.1.1
    - flake8-logging-format==0.6.0
    - flake8-mutable==1.2.0
    - flake8-pie==0.15.0
    - flake8-polyfill==1.0.2
    - flake8-quotes==3.3.1
    - flake8-string-format==0.3.0
    - flake8-tidy-imports==4.6.0
    - flake8-variables-names==0.0.4
    - pep8-naming==0.12.1
    - flake8-deprecated==1.3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
    language_version: python
    args:
    - --maxkb=500
  - id: trailing-whitespace
    language_version: python
    args: [--markdown-linebreak-ext=md]
  - id: check-merge-conflict
    language_version: python
  - id: check-case-conflict
    language_version: python
  - id: check-symlinks
    language_version: python
  - id: end-of-file-fixer
    language_version: python
  - id: check-toml
- repo: https://github.com/dhruvmanila/remove-print-statements
  rev: v0.5.2
  hooks:
  - id: remove-print-statements
    args: [--verbose, --dry-run]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
    exclude: .*/dependabot.yml
