repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.1
  hooks:
  - id: mypy
    name: Lint code (mypy)
    language: python
    types: [python]
    require_serial: true
    args: [--config-file=pyproject.toml]
    additional_dependencies: [qgis-stubs]
    exclude: (.*/plugin\.py)|(.*/provider\.py)|(.*/test.*)|(PolygonsParallelToLine/__init__\.py)
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.0
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
    language_version: python
    args:
    - --maxkb=500
  - id: trailing-whitespace
    language_version: python
    args: [--markdown-linebreak-ext=md]
  - id: check-merge-conflict
    language_version: python
  - id: check-case-conflict
    language_version: python
  - id: check-symlinks
    language_version: python
  - id: end-of-file-fixer
    language_version: python
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
    exclude: .*/dependabot.yml
  - id: pretty-format-toml
    args: [--autofix]
