services:
  qgis-docker:
    build:
      dockerfile: Dockerfile
    image: qgis-for-pptl:ci
    container_name: qgis_pptl
    volumes:
    - type: bind
      source: .
      target: /pptl
    environment:
    - PYTHONPATH=/pptl
    - PPTL_TEST=1
    command: tail -f /dev/null
