[tool.poetry]
name = "polygons-parallel-to-line"
version = "0.1.0"
description = ""
authors = ["Andrii Liekariev <elfpkck@gmail.com>"]
readme = "README.md"
packages = [{include = "polygons_parallel_to_line"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
