name: PR Validation
on:
  workflow_dispatch:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
jobs:
  precommit:
    name: Static Analysis/Linting/Prettifier
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --color=always --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
    - name: Launching docker compose
      run: docker compose -f docker-compose.yml up -d --force-recreate --remove-orphans
    - name: Running tests
      run: docker exec -t qgis_pptl sh -c "pytest /pptl/tests --qgis_disable_gui"
