name: PR Validation
on:
  workflow_dispatch:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
jobs:
  precommit:
    name: Static Analysis/Linting/Prettifier
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --color=always --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
    - name: Build Docker image
      run: make build
    - name: Start Docker container
      run: make run
    - name: Running tests with coverage
      run: make test-coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: Elfpkck/polygons_parallel_to_line
        fail_ci_if_error: false
    - name: Cleanup
      if: always()
      run: make clean
